### ISSUE TITLE
some errors were occurred when starting the syncChanges.service

### ISSUE THREAD

**Issue by zhanghanting** [mganss/SyncChanges#113]
Dear Michael Ganss mganss,sorry to trouble you!some errors were occurred when starting the syncChanges.service,errors are as follows:
 System.IO.FileNotFoundException
   在 System.IO.__Error.WinIOError(Int32, System.String)
   在 System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   在 System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   在 System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32, Boolean)
   在 System.IO.File.InternalReadAllText(System.String, System.Text.Encoding, Boolean)
   在 SyncChanges.Service.SyncChanges+<OnStart>d__5.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()

I`m  looking forward to your reply,please,thanks a lot!

**Comment by mganss** [comment]
It looks like the service can't find the configuration file. It needs to be named `config.json` and be placed in the same folder as the service executable.

**Comment by zhanghanting** [comment]
thank you,it works!
