### ISSUE TITLE
Is the Change Tracking suitable for 3-tier application?

### ISSUE THREAD

**Issue by tht245806497** [mganss/SyncChanges#154]
The CHANGETABLE(CHANGES ...) function seems not good for paging.
If one transaction update 10, 000, 000 records, the SYS_CHANGE_VERSION column is same version number.
Do you have any suggestions for this？

**Comment by mganss** [comment]
SyncChanges doesn't do paging of changes, it reads all changes in one pass into memory. Have you run into problems?

**Comment by tht245806497** [comment]
To be exact, it's not SyncChanges problem. 
If the table has more than 10,000,000 records and the current change tracking version is 100:

After run the update  sql "Update TableName Set FieldName=Value"，the CHANGETABLE(CHANGES TableName, 100) function will return 10, 000, 000 records, and the SYS_CHANGE_VERSION field of all records is 101.

There can't load the all changes into memory in this situation.  I'm looking for a batch solution.

**Comment by mganss** [comment]
Yes, SyncChanges wasn't built for these kinds of scenarios. Like you said, it's probably best to try and accomodate SyncChanges by performing the updates in a more sequential way.
