### ISSUE TITLE
Doesn't Create SyncInfo

### ISSUE THREAD

**Issue by USER-NAME-ERROR-0fx** [mganss/SyncChanges#2]
Doesn't create Syncinfo table. Had to move:
`SetSyncVersion`
To After:
`Log.Info($"SyncInfo table does not exist in database {dbInfo.Name}");`

**Comment by mganss** [comment]
The SyncInfo table will be created [after the first replication](https://github.com/mganss/SyncChanges/blob/ca32ba067442e7adab3b8f71de2981f7b7670157/SyncChanges/Synchronizer.cs#L325-L329) has occurred. So I don't think that's a bug. Please elaborate if you think otherwise. Thanks.
