### ISSUE TITLE
Source will/should be greater than destination?

### ISSUE THREAD

**Issue by USER-NAME-ERROR-0fx** [mganss/SyncChanges#3]
If minVersion is the source DB's current minumum version. Destination Version is the destination. On first run it is 0. thus 
 if (minVersion > destinationVersion)
Will stop the thing from running

**Comment by mganss** [comment]
The minimum version of the source DB is the version up to which it has change information. If this is greater than the current version of the destination DB, there is a "gap" which cannot be filled by the change information the source DB has, in other words the destination DB is too old. You must start out with a version of the destination DB that's recent enough.

Note that the minVersion is not the current version of the source DB, i.e. if you're starting with a DB you have just created, then insert a few rows, the minVersion will still be 0, making it possible to replicate the inserts to an empty destination DB (whose current version is 0).

**Comment by gmspel** [comment]
Is the minimum version of  the source db is greater than the destination, wouldn't that simply mean you want to flush all changes between the destination and the source?
So, Source has been spinning away updaing itself, but the sync was "off". Your turn sync on, the destination db is low (say 100) and the source is high (say 2000), wouldn't you simply want to extract all the ids that had a change id between 100 and 2000?

**Comment by mganss** [comment]
There are two values: 
- the minimum version (the lowest version back to which change information is available in the source DB)
- the current version

In your example, I assume that 100 is the current version of the destination DB and 2000 is the minimum version of the source DB (its current version is higher, let's say 3000). In this scenario, the source DB has no information on how to change from current version 100 to current version 2000 making it impossible to synchronize the two DBs.

This means you have to start over, i.e. restore a backup of the source DB on the destination DB, then start to sync changes again.

The parameter that governs what the minimum version will be is the `CHANGE_RETENTION` parameter described [here](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/enable-and-disable-change-tracking-sql-server):

> The change retention value specifies the time period for which change tracking information is kept. Change tracking information that is older than this time period is removed periodically. When you are setting this value, you should consider how often applications will synchronize with the tables in the database. The specified retention period must be at least as long as the maximum time period between synchronizations. If an application obtains changes at longer intervals, the results that are returned might be incorrect because some of the change information has probably been removed. To avoid obtaining incorrect results, an application can use the CHANGE_TRACKING_MIN_VALID_VERSION system function to determine whether the interval between synchronizations has been too long.
