### ISSUE TITLE
Trying to run the console application

### ISSUE THREAD

**Issue by AJFiori** [mganss/SyncChanges#4]
Hi, I'm trying to run the console application and the log file keeps saying 
2018-12-07 15:45:42.9303|ERROR|No config files supplied 
I edited the json file and made it be config.json and there is an app.config in the folder. Not sure if I did something incorrectly . This is my Json file

```json
{
  "ReplicationSets": [
    {
      "Name": "SyncTest",
      "Source": {
        "Name": "SyncTest",
        "ConnectionString": "Data Source=A-10\SQLEXPRESS;Initial Catalog=Test;Integrated Security=True;MultipleActiveResultSets=True"
      },
      "Destinations": [
        {
          "Name": "SyncTest",
          "ConnectionString": "Data Source=A-10\\SQLEXPRESS01;Initial Catalog=Test;Integrated Security=True;MultipleActiveResultSets=True"
        }
```

**Comment by mganss** [comment]
The configuration file has to be specified as a command line argument, e.g.
```
SyncChanges.exe .\config.json
```
Also, the config.json you posted lacks the closing `] } ] }` and you have to escape the backslash in the first connection string.
