### ISSUE TITLE
Is there a perbuild can be used directly?

### ISSUE THREAD

**Issue by dry11orange** [mganss/SyncChanges#76]

**Comment by mganss** [comment]
Yes, every release at https://github.com/mganss/SyncChanges/releases contains binary zips for both the console application and the service. The service can be installed as described here: https://github.com/mganss/SyncChanges#service Usage of the console application is described here: https://github.com/mganss/SyncChanges#usage

**Comment by dry11orange** [comment]
No, there is source code only, I find nothing like binary,

**Comment by mganss** [comment]
You're right. The zips are not included in the intermediate releases on GitHub. You can find them on AppVeyor: https://ci.appveyor.com/project/mganss/syncchanges/branch/master/artifacts

**Comment by dry11orange** [comment]
ok, Thank you!
