### ISSUE TITLE
2021-04-02 10:59:53.5602|ERROR|No config files supplied 

### ISSUE THREAD

**Issue by zhanghanting** [mganss/SyncChanges#84]
I created a config.json file ,but when  I execute the windows .exe service causing an error that 2021-04-02 10:59:53.5602|ERROR|No config files supplied.can you give me hand?need I do other config?

**Comment by mganss** [comment]
It seems you are using the console application not the Windows service. If you intend to use the console application, the path to the config file needs to be given on the commandline, e.g.

```
SyncChanges.Console.exe config.json
```

If you intend to use the Windows service, it needs to be installed as described here: https://github.com/mganss/SyncChanges#service

In this case the configuration file needs to be located in the same directory as the service executable (SyncChanges.Service.exe).

**Comment by zhanghanting** [comment]
thank you,I will try

**Comment by mganss** [comment]
I'm closing this. Feel free to reopen if the issue persists.
