### ISSUE TITLE
what`s the difference between the console application and the windows servcice?

### ISSUE THREAD

**Issue by zhanghanting** [mganss/SyncChanges#85]
handsome,I`m sorry to distrub you but some issue want to consult you that means a lot to me.could you tell me what`s the difference between these two ways?Now,I wanna synchronize data from one sqlserver database to another sqlserver database based on log in real time ,which way is more suitable?please please please

**Comment by mganss** [comment]
The console application is a good choice for one-off invocations, when you want to sync through the task scheduler or for testing purposes. The Windows service is the best choice if you want to synchronize permanently so I think it's probably best for your use case. I'd suggest to try with the console application first to see if everything works and then set up the Windows service for permanent use.

**Comment by zhanghanting** [comment]
Dear Mr Michael Ganss magnss,thank you for your  reply with patience！I tried the console application in my windows occured some fatal errors,its details are that "Error synchronizing databases for configuration config.json System.ArgumentException: doesn`t support  the keyword: databasename" .There is  something wrong with my config.json file.My config.json file reads as follows:
{
  "ReplicationSets": [
    {
      "Name": "Test",
      "Source": {
        "Name": "Primary",
        "ConnectionString": "Data Source=jdbc:microsoft:sqlserver://192.168.1.195:1433;databasename=test;Initial Catalog=test;Integrated Security=True;MultipleActiveResultSets=True"
      },
      "Destinations": [
        {
          "Name": "Secondary 1",
          "ConnectionString": "Data Source=jdbc:microsoft:sqlserver://192.168.1.180:1433;databasename=test;Initial Catalog=test;Integrated Security=True;MultipleActiveResultSets=True"
        }
      ],
      "Tables": [ "[dbo].[db_table5]"]
    }
  ]
}
  could you please help me revise it?

**Comment by mganss** [comment]
Your connection strings look strange. A regular SQL Server connection string looks more like this:

```
"Data Source=192.168.1.195;Initial Catalog=test;Integrated Security=True;MultipleActiveResultSets=True"
```

**Comment by zhanghanting** [comment]
thanks, I tried it based on your connection string  and I pointed username and password.it worked but meeting some problems that reads as follows:
|ERROR|Cannot replicate table [dbo].[db_student] to destination Secondary 1 because minimum source version 2 is greater than destination version 0
  Have you ever encountered this problem?

**Comment by zhanghanting** [comment]
I created two new databases to synchronize,no problem about version but a new strange problem occurred.It says cannot do the set operation in the destination secondary system for it lacking an identity attribute in the table dbo.t_student that is the destination table.But I specified the primary key when I created the table dbo.t_student.If you have meet the similar problem,please give me some advice.thanks a lot!

**Comment by mganss** [comment]
> |ERROR|Cannot replicate table [dbo].[db_student] to destination Secondary 1 because minimum source version 2 is greater than destination version 0
> Have you ever encountered this problem?

Yes, it means the source database does not contain enough change tracking information that would allow synchronization of the destination database. In particular, the changes from version 0 to version 2 are not available within the source database. These changes are necessary because the destination database is at version 0. Perhaps the [`CHANGE_RETENTION`](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/enable-and-disable-change-tracking-sql-server?view=sql-server-ver15) period has passed since synchronization was last performed?

**Comment by mganss** [comment]
> I created two new databases to synchronize,no problem about version but a new strange problem occurred.It says cannot do the set operation in the destination secondary system for it lacking an identity attribute in the table dbo.t_student that is the destination table.But I specified the primary key when I created the table dbo.t_student.If you have meet the similar problem,please give me some advice.thanks a lot!

What's the exact error message you're getting?

**Comment by zhanghanting** [comment]
the key message of error is that  "lacking an identity attribute in the table dbo.t_student that is the destination table caused cannot do the set operation",which is translated from my native language!In the process of synchronization,it needs to assign the values of the original table to the target table,which should be the reference to the set operation.

**Comment by zhanghanting** [comment]
> > I created two new databases to synchronize,no problem about version but a new strange problem occurred.It says cannot do the set operation in the destination secondary system for it lacking an identity attribute in the table dbo.t_student that is the destination table.But I specified the primary key when I created the table dbo.t_student.If you have meet the similar problem,please give me some advice.thanks a lot!
> 
> What's the exact error message you're getting?

the key message of error is that "lacking an identity attribute in the table dbo.t_student that is the destination table caused cannot do the set operation",which is translated from my native language!In the process of synchronization,it needs to assign the values of the original table to the target table,which should be the reference to the set operation.

**Comment by zhanghanting** [comment]
> > |ERROR|Cannot replicate table [dbo].[db_student] to destination Secondary 1 because minimum source version 2 is greater than destination version 0
> > Have you ever encountered this problem?
> 
> Yes, it means the source database does not contain enough change tracking information that would allow synchronization of the destination database. In particular, the changes from version 0 to version 2 are not available within the source database. These changes are necessary because the destination database is at version 0. Perhaps the [`CHANGE_RETENTION`](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/enable-and-disable-change-tracking-sql-server?view=sql-server-ver15) period has passed since synchronization was last performed?

I didn`t set the CHANGE_RETENTION.How does it changed its version?Update or insert operation goes with  a new version?It likely that the version of destination always smaller than that of Source.

**Comment by mganss** [comment]
> the key message of error is that "lacking an identity attribute in the table dbo.t_student that is the destination table caused cannot do the set operation",which is translated from my native language!In the process of synchronization,it needs to assign the values of the original table to the target table,which should be the reference to the set operation.

Please paste the exception message and stack trace from the SyncChanges log file here.

**Comment by mganss** [comment]
> I didn`t set the CHANGE_RETENTION.How does it changed its version?Update or insert operation goes with a new version?It likely that the version of destination always smaller than that of Source.

By default the retention period is two days. 

The version changes whenever an insert, update, or delete is executed. 

The current 
version of the destination will always be less than or equal to the *current* version of the source but it must not be less than the *minimum* version of the source.

**Comment by zhanghanting** [comment]
> > the key message of error is that "lacking an identity attribute in the table dbo.t_student that is the destination table caused cannot do the set operation",which is translated from my native language!In the process of synchronization,it needs to assign the values of the original table to the target table,which should be the reference to the set operation.
> 
> Please paste the exception message and stack trace from the SyncChanges log file here.
okay ,the exception message and stack trace are as follows:

`2021-04-27 14:29:33.3341|DEBUG|Executing insert: set IDENTITY_INSERT [dbo].[t_student] ON; insert into [dbo].[t_student] ([id], [age], [name]) values (@0, @1, @2); set IDENTITY_INSERT [dbo].[t_student] OFF (@0 = 2, @1 = 33, @2 = curry) 
2021-04-27 14:29:33.3499|ERROR|Error replicating changes to destination Secondary System.Data.SqlClient.SqlException (0x80131904): 表 'dbo.t_student' 没有标识属性。无法执行 SET 操作。
   在 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   在 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   在 System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   在 System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   在 SyncChanges.Synchronizer.PerformChange(Database db, Change change)
   在 SyncChanges.Synchronizer.Replicate(DatabaseInfo source, IGrouping`2 destinations, IList`1 tables)
ClientConnectionId:72512ecf-2f2c-4903-b1e2-c9491e770621
Error Number:8106,State:1,Class:16 HelpLink.ProdName: Microsoft SQL Server;HelpLink.ProdVer: 10.50.1600;HelpLink.EvtSrc: MSSQLServer;HelpLink.EvtID: 8106;HelpLink.BaseHelpUrl: http://go.microsoft.com/fwlink;HelpLink.LinkId: 20476
2021-04-27 14:29:33.4022|INFO|Finished replication with errors 
2021-04-27 14:39:29.9090|INFO|Getting replication information for replication set Test 
2021-04-27 14:39:30.7707|INFO|Replicating table [dbo].[t_student] 
2021-04-27 14:39:30.7707|INFO|Starting replication for replication set Test 
2021-04-27 14:39:30.7932|INFO|Database Secondary is at version 0 
2021-04-27 14:39:30.8247|INFO|Snapshot isolation is enabled in database Primary 
2021-04-27 14:39:30.8402|INFO|Current version of database Primary is 1 
2021-04-27 14:39:30.9192|INFO|Minimum version of table [dbo].[t_student] in database Primary is 0 
2021-04-27 14:39:30.9192|DEBUG|Retrieving changes for table [dbo].[t_student]: select c.SYS_CHANGE_OPERATION, c.SYS_CHANGE_VERSION, c.SYS_CHANGE_CREATION_VERSION,
                        c.[id], t.[age], t.[name]
                        from CHANGETABLE (CHANGES [dbo].[t_student], @0) c
                        left outer join [dbo].[t_student] t on c.[id] = t.[id] order by coalesce(c.SYS_CHANGE_CREATION_VERSION, c.SYS_CHANGE_VERSION) `

**Comment by zhanghanting** [comment]
> > I didn`t set the CHANGE_RETENTION.How does it changed its version?Update or insert operation goes with a new version?It likely that the version of destination always smaller than that of Source.
> 
> By default the retention period is two days.
> 
> The version changes whenever an insert, update, or delete is executed.
> 
> The current
> version of the destination will always be less than or equal to the _current_ version of the source but it must not be less than the _minimum_ version of the source.

Thank you ,got it.

**Comment by zhanghanting** [comment]
> > the key message of error is that "lacking an identity attribute in the table dbo.t_student that is the destination table caused cannot do the set operation",which is translated from my native language!In the process of synchronization,it needs to assign the values of the original table to the target table,which should be the reference to the set operation.
> 
> Please paste the exception message and stack trace from the SyncChanges log file here.

[log.txt](https://github.com/mganss/SyncChanges/files/6395787/log.txt)

**Comment by mganss** [comment]
The table has no [identity](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15) column. I've made a new release (2.1.308) that allows for tables without identity columns. Please try again with the latest release.

**Comment by zhanghanting** [comment]
okay,but I pointed the primary key when creating table.

**Comment by zhanghanting** [comment]
> > I didn`t set the CHANGE_RETENTION.How does it changed its version?Update or insert operation goes with a new version?It likely that the version of destination always smaller than that of Source.
> 
> By default the retention period is two days.
> 
> The version changes whenever an insert, update, or delete is executed.
> 
> The current
> version of the destination will always be less than or equal to the _current_ version of the source but it must not be less than the _minimum_ version of the source.

I  had the same problem again today that reads as follows:
"|ERROR|Cannot replicate table [dbo].[t_student] to destination Secondary1 because minimum source version 1 is greater than destination version 0".How do you solve the problem usually?

**Comment by zhanghanting** [comment]
> The table has no [identity](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15) column. I've made a new release (2.1.308) that allows for tables without identity columns. Please try again with the latest release.

I`ve tried the new realease and it`s working.And can it synchronize historyical data?

**Comment by zhanghanting** [comment]
> The table has no [identity](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15) column. I've made a new release (2.1.308) that allows for tables without identity columns. Please try again with the latest release.

can it sychronize data in real time(delays at the millisecond level) when using the windows service way?If you`ve tried it in your production environment,please tell me whether it will be affected by the amount of data in tables of database?

**Comment by zhanghanting** [comment]
Many thanks for your patience answer,it`s useful for me so much!
