### ISSUE TITLE
Install the SyncChanges as the Windows Service

### ISSUE THREAD

**Issue by zhanghanting** [mganss/SyncChanges#90]
I failed to install the SyncChanges as a windows service according to your documentation.I  run the command instruct("C:\Windows\Microsoft.NET\Framework64\v4.0.30319\InstallUtil.exe .\SyncChanges.Service.exe").During installation,it  necessary to enter credentials for the user account the service will use.I tried my database account(username:sa  password:123456) and my computer login account,but all failed.The exception message is that System.CompenentModel.Win32Exception is refused to access.The SyncChanges.Service.InstallLog is included below.
[SyncChanges.Service.InstallLog.txt](https://github.com/mganss/SyncChanges/files/6432538/SyncChanges.Service.InstallLog.txt)

**Comment by mganss** [comment]
Did you specify the username as a fully qualified name by prefixing the name with `.\`, for example `.\Admin`? The account is the machine account the service will run as, not the SQL Server account (the latter needs to be specified in the config.json).

Try installing from an elevated command prompt ("run as Administrator"). Also, this might help: https://stackoverflow.com/a/15502739/1970064

**Comment by zhanghanting** [comment]
Yes,I specified a fully qualified username with .\ as the prefix(.\DELL),DELL is my administrator account of my computer.In addition,I created a new adminstrator account to test,but failed too!

**Comment by zhanghanting** [comment]
> Did you specify the username as a fully qualified name by prefixing the name with `.\`, for example `.\Admin`? The account is the machine account the service will run as, not the SQL Server account (the latter needs to be specified in the config.json).
> 
> Try installing from an elevated command prompt ("run as Administrator"). Also, this might help: https://stackoverflow.com/a/15502739/1970064

Thanks a lot for your advice,I just made it!I`ll try it in our production  environment later!thank,thank,thank very much!
